name: Renovate

on:
  schedule:
    - cron: '0 0 * * *'

concurrency:
  group: ${{github.workflow}}-${{github.ref}}
  cancel-in-progress: true

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v43.0.17
        env:
          RENOVATE_TOKEN: ${{secrets.GITHUB_TOKEN}}